# Change these first
owner: thepeerstack # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Backend API
    url: https://api.thepeer.co/api/health
    icon: https://thepeer.co/favicon.ico
  - name: ThePeer Website
    url: https://thepeer.co
assignees: # Users to assign downtime issues (optional)
  - ichtrojan
  - nerdeveloper


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thepeer.co
  # baseUrl: /your-repo-name
  logoUrl:
  name: ThePeer
  introTitle: "**ThePeer** is a fintech platform that enables their customers seamlessly send money from one fintech to another"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/thepeerstack/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
